name: sab
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.2
  scoped_model: ^0.2.0
  rxdart: ^0.18.1

dev_dependencies:
  shared_preferences: ^0.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - resources/
  fonts:
    - family: kufi
      fonts:
        - asset: resources/kufi.ttf